version: "3.8"
services:
    askforthemoon-mongo:
        container_name: askforthemoon-mongo
        image: mongo:7.0.9
        command: --port 8089
        ports:
            - "8089:8089"
        restart: always
        volumes:
            - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
            - ./db-dump.gz:/db-dump.gz
